apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sanjayleo35/jerney.git'
    targetRevision: devops
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jerney
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m