apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerney-db-pvc
  namespace: jerney
  labels:
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jerney-ebs-sc
  resources:
    requests:
      storage: 10Gi
