apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jerney-ebs-sc
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
